export const SHARED_TOKENS = {
  RABBITMQ_CONNECTION_FACTORY: 'RABBITMQ_CONNECTION_FACTORY',
  SERVICE_REGISTRY: 'SERVICE_REGISTRY',
  MAIN_LOGGER: 'MAIN_LOGGER',
  EXPRESS_APP: 'EXPRESS_APP',
  DEBUG: 'APP_DEBUGGING',
};
